extend = [{ path = "../cargo-make/main.toml" }]

[tasks.fmt-all]
script = '''
#!@duckscript
leptosfmt .
cargo fmt --all
cargo clippy --fix -- -D warnings
'''


[tasks.check]
script = '''
#!@duckscript
leptosfmt --check .
cargo fmt --all --check
cargo clippy -- -D warnings
'''
