[tasks.fmt-all]
script = '''
leptosfmt .
cargo fmt --all
cargo clippy --fix -- -D warnings
'''


[tasks.check]
script = '''
leptosfmt --check .
cargo fmt --all --check
cargo clippy -- -D warnings
'''
