[watch]
ignore = [
    ".git",
    ".githooks",
    "style",
    "extras",
    "gen_assets",
    "src/extras",
    "build.rs",
]

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "npx tailwindcss -i input.css -o style/output.css"]
