name: Deploy on new sitemap
on:
  workflow_dispatch:
  repository_dispatch:
    types: [sitemap_changed]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  post_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
      - name: Update submodule
        run: |
          git submodule update --remote
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2024-02-12
          target: wasm32-unknown-unknown
          override: true

      - uses: Swatinem/rust-cache@v2
      - uses: davidB/rust-cargo-make@v1

      - name: Pre Build
        run: |
          npm i
      - name: Build
        run: cargo make build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist

  post_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: post_build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
